main: com.alexlabbane.blocksolver.BlockSolver
api: spigot
api-version: 1.16
name: BlockSolver
version: '1.0'
author: Alex Labbane

commands:
  blocksolver:
    description: All commands for blocksolver